<?php

/**
 * BaseImageUsage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property integer $width
 * @property integer $height
 * @property boolean $background
 * @property string $background_color
 * 
 * @method string     getTitle()            Returns the current record's "title" value
 * @method string     getDescription()      Returns the current record's "description" value
 * @method integer    getWidth()            Returns the current record's "width" value
 * @method integer    getHeight()           Returns the current record's "height" value
 * @method boolean    getBackground()       Returns the current record's "background" value
 * @method string     getBackgroundColor()  Returns the current record's "background_color" value
 * @method ImageUsage setTitle()            Sets the current record's "title" value
 * @method ImageUsage setDescription()      Sets the current record's "description" value
 * @method ImageUsage setWidth()            Sets the current record's "width" value
 * @method ImageUsage setHeight()           Sets the current record's "height" value
 * @method ImageUsage setBackground()       Sets the current record's "background" value
 * @method ImageUsage setBackgroundColor()  Sets the current record's "background_color" value
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImageUsage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('image_usage');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('width', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('height', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('background', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('background_color', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}