<?php

/**
 * BaseTweet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tweet_monitor_id
 * @property string $twitter_id
 * @property date $date_published
 * @property string $content
 * @property string $url
 * @property string $avatar
 * @property string $author
 * @property string $author_url
 * @property TweetMonitor $TweetMonitor
 * 
 * @method integer      getTweetMonitorId()   Returns the current record's "tweet_monitor_id" value
 * @method string       getTwitterId()        Returns the current record's "twitter_id" value
 * @method date         getDatePublished()    Returns the current record's "date_published" value
 * @method string       getContent()          Returns the current record's "content" value
 * @method string       getUrl()              Returns the current record's "url" value
 * @method string       getAvatar()           Returns the current record's "avatar" value
 * @method string       getAuthor()           Returns the current record's "author" value
 * @method string       getAuthorUrl()        Returns the current record's "author_url" value
 * @method TweetMonitor getTweetMonitor()     Returns the current record's "TweetMonitor" value
 * @method Tweet        setTweetMonitorId()   Sets the current record's "tweet_monitor_id" value
 * @method Tweet        setTwitterId()        Sets the current record's "twitter_id" value
 * @method Tweet        setDatePublished()    Sets the current record's "date_published" value
 * @method Tweet        setContent()          Sets the current record's "content" value
 * @method Tweet        setUrl()              Sets the current record's "url" value
 * @method Tweet        setAvatar()           Sets the current record's "avatar" value
 * @method Tweet        setAuthor()           Sets the current record's "author" value
 * @method Tweet        setAuthorUrl()        Sets the current record's "author_url" value
 * @method Tweet        setTweetMonitor()     Sets the current record's "TweetMonitor" value
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTweet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tweet');
        $this->hasColumn('tweet_monitor_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('twitter_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('date_published', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('content', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('avatar', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('author_url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TweetMonitor', array(
             'local' => 'tweet_monitor_id',
             'foreign' => 'id'));
    }
}