<?php

/**
 * BaseRelatedAsset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $parent_asset_id
 * @property integer $asset_id
 * @property string $type
 * @property string $description
 * @property boolean $is_active
 * @property integer $display_order
 * @property Asset $ParentAsset
 * @property Asset $Asset
 * 
 * @method integer      getParentAssetId()   Returns the current record's "parent_asset_id" value
 * @method integer      getAssetId()         Returns the current record's "asset_id" value
 * @method string       getType()            Returns the current record's "type" value
 * @method string       getDescription()     Returns the current record's "description" value
 * @method boolean      getIsActive()        Returns the current record's "is_active" value
 * @method integer      getDisplayOrder()    Returns the current record's "display_order" value
 * @method Asset        getParentAsset()     Returns the current record's "ParentAsset" value
 * @method Asset        getAsset()           Returns the current record's "Asset" value
 * @method RelatedAsset setParentAssetId()   Sets the current record's "parent_asset_id" value
 * @method RelatedAsset setAssetId()         Sets the current record's "asset_id" value
 * @method RelatedAsset setType()            Sets the current record's "type" value
 * @method RelatedAsset setDescription()     Sets the current record's "description" value
 * @method RelatedAsset setIsActive()        Sets the current record's "is_active" value
 * @method RelatedAsset setDisplayOrder()    Sets the current record's "display_order" value
 * @method RelatedAsset setParentAsset()     Sets the current record's "ParentAsset" value
 * @method RelatedAsset setAsset()           Sets the current record's "Asset" value
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRelatedAsset extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('related_asset');
        $this->hasColumn('parent_asset_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('asset_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Asset as ParentAsset', array(
             'local' => 'asset_id',
             'foreign' => 'id'));

        $this->hasOne('Asset', array(
             'local' => 'asset_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}