<?php

/**
 * BaseRelatedAssetType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property boolean $is_active
 * 
 * @method string           getTitle()       Returns the current record's "title" value
 * @method string           getDescription() Returns the current record's "description" value
 * @method boolean          getIsActive()    Returns the current record's "is_active" value
 * @method RelatedAssetType setTitle()       Sets the current record's "title" value
 * @method RelatedAssetType setDescription() Sets the current record's "description" value
 * @method RelatedAssetType setIsActive()    Sets the current record's "is_active" value
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRelatedAssetType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('related_asset_type');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}