<?php

/**
 * BaseAssetAudio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $asset_id
 * @property string $file
 * @property string $original_file
 * @property string $genre
 * @property string $source
 * @property string $author
 * @property string $interpret
 * @property string $composer
 * @property string $year
 * @property string $label
 * @property string $extension
 * @property string $original_file_size
 * @property string $duration
 * @property Asset $Asset
 * 
 * @method integer    getAssetId()            Returns the current record's "asset_id" value
 * @method string     getFile()               Returns the current record's "file" value
 * @method string     getOriginalFile()       Returns the current record's "original_file" value
 * @method string     getGenre()              Returns the current record's "genre" value
 * @method string     getSource()             Returns the current record's "source" value
 * @method string     getAuthor()             Returns the current record's "author" value
 * @method string     getInterpret()          Returns the current record's "interpret" value
 * @method string     getComposer()           Returns the current record's "composer" value
 * @method string     getYear()               Returns the current record's "year" value
 * @method string     getLabel()              Returns the current record's "label" value
 * @method string     getExtension()          Returns the current record's "extension" value
 * @method string     getOriginalFileSize()   Returns the current record's "original_file_size" value
 * @method string     getDuration()           Returns the current record's "duration" value
 * @method Asset      getAsset()              Returns the current record's "Asset" value
 * @method AssetAudio setAssetId()            Sets the current record's "asset_id" value
 * @method AssetAudio setFile()               Sets the current record's "file" value
 * @method AssetAudio setOriginalFile()       Sets the current record's "original_file" value
 * @method AssetAudio setGenre()              Sets the current record's "genre" value
 * @method AssetAudio setSource()             Sets the current record's "source" value
 * @method AssetAudio setAuthor()             Sets the current record's "author" value
 * @method AssetAudio setInterpret()          Sets the current record's "interpret" value
 * @method AssetAudio setComposer()           Sets the current record's "composer" value
 * @method AssetAudio setYear()               Sets the current record's "year" value
 * @method AssetAudio setLabel()              Sets the current record's "label" value
 * @method AssetAudio setExtension()          Sets the current record's "extension" value
 * @method AssetAudio setOriginalFileSize()   Sets the current record's "original_file_size" value
 * @method AssetAudio setDuration()           Sets the current record's "duration" value
 * @method AssetAudio setAsset()              Sets the current record's "Asset" value
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAssetAudio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asset_audio');
        $this->hasColumn('asset_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('original_file', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('genre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('source', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('interpret', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('composer', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('year', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('label', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('extension', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('original_file_size', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('duration', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Asset', array(
             'local' => 'asset_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}