<?php

/**
 * BaseTweetMonitor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $query
 * @property Doctrine_Collection $Tweets
 * 
 * @method string              getQuery()  Returns the current record's "query" value
 * @method Doctrine_Collection getTweets() Returns the current record's "Tweets" collection
 * @method TweetMonitor        setQuery()  Sets the current record's "query" value
 * @method TweetMonitor        setTweets() Sets the current record's "Tweets" collection
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTweetMonitor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tweet_monitor');
        $this->hasColumn('query', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tweet as Tweets', array(
             'local' => 'id',
             'foreign' => 'tweet_monitor_id'));
    }
}