<?php

/**
 * BaseAssetVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $asset_id
 * @property string $youtube_id
 * @property string $youtube_thumb
 * @property string $file
 * @property string $original_file
 * @property string $headline
 * @property string $genre
 * @property string $source
 * @property string $author
 * @property string $width
 * @property string $height
 * @property string $extension
 * @property string $original_file_size
 * @property string $frame_rate
 * @property string $bitrate
 * @property string $duration
 * @property string $start_from
 * @property Asset $Asset
 * @property Doctrine_Collection $VideoDropboxes
 * 
 * @method integer             getAssetId()            Returns the current record's "asset_id" value
 * @method string              getYoutubeId()          Returns the current record's "youtube_id" value
 * @method string              getYoutubeThumb()       Returns the current record's "youtube_thumb" value
 * @method string              getFile()               Returns the current record's "file" value
 * @method string              getOriginalFile()       Returns the current record's "original_file" value
 * @method string              getHeadline()           Returns the current record's "headline" value
 * @method string              getGenre()              Returns the current record's "genre" value
 * @method string              getSource()             Returns the current record's "source" value
 * @method string              getAuthor()             Returns the current record's "author" value
 * @method string              getWidth()              Returns the current record's "width" value
 * @method string              getHeight()             Returns the current record's "height" value
 * @method string              getExtension()          Returns the current record's "extension" value
 * @method string              getOriginalFileSize()   Returns the current record's "original_file_size" value
 * @method string              getFrameRate()          Returns the current record's "frame_rate" value
 * @method string              getBitrate()            Returns the current record's "bitrate" value
 * @method string              getDuration()           Returns the current record's "duration" value
 * @method string              getStartFrom()          Returns the current record's "start_from" value
 * @method Asset               getAsset()              Returns the current record's "Asset" value
 * @method Doctrine_Collection getVideoDropboxes()     Returns the current record's "VideoDropboxes" collection
 * @method AssetVideo          setAssetId()            Sets the current record's "asset_id" value
 * @method AssetVideo          setYoutubeId()          Sets the current record's "youtube_id" value
 * @method AssetVideo          setYoutubeThumb()       Sets the current record's "youtube_thumb" value
 * @method AssetVideo          setFile()               Sets the current record's "file" value
 * @method AssetVideo          setOriginalFile()       Sets the current record's "original_file" value
 * @method AssetVideo          setHeadline()           Sets the current record's "headline" value
 * @method AssetVideo          setGenre()              Sets the current record's "genre" value
 * @method AssetVideo          setSource()             Sets the current record's "source" value
 * @method AssetVideo          setAuthor()             Sets the current record's "author" value
 * @method AssetVideo          setWidth()              Sets the current record's "width" value
 * @method AssetVideo          setHeight()             Sets the current record's "height" value
 * @method AssetVideo          setExtension()          Sets the current record's "extension" value
 * @method AssetVideo          setOriginalFileSize()   Sets the current record's "original_file_size" value
 * @method AssetVideo          setFrameRate()          Sets the current record's "frame_rate" value
 * @method AssetVideo          setBitrate()            Sets the current record's "bitrate" value
 * @method AssetVideo          setDuration()           Sets the current record's "duration" value
 * @method AssetVideo          setStartFrom()          Sets the current record's "start_from" value
 * @method AssetVideo          setAsset()              Sets the current record's "Asset" value
 * @method AssetVideo          setVideoDropboxes()     Sets the current record's "VideoDropboxes" collection
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAssetVideo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asset_video');
        $this->hasColumn('asset_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('youtube_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('youtube_thumb', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('original_file', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('headline', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('genre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('source', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('width', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('height', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('extension', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('original_file_size', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('frame_rate', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('bitrate', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('duration', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('start_from', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Asset', array(
             'local' => 'asset_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('VideoDropbox as VideoDropboxes', array(
             'local' => 'id',
             'foreign' => 'asset_video_id'));
    }
}