<?php

/**
 * BaseAssetPerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $asset_id
 * @property string $type
 * @property string $name
 * @property string $headline
 * @property date $dob
 * @property text $bio
 * @property string $website_url
 * @property string $facebook_url
 * @property string $twitter_url
 * @property string $youtube_url
 * @property Asset $Asset
 * 
 * @method integer     getAssetId()      Returns the current record's "asset_id" value
 * @method string      getType()         Returns the current record's "type" value
 * @method string      getName()         Returns the current record's "name" value
 * @method string      getHeadline()     Returns the current record's "headline" value
 * @method date        getDob()          Returns the current record's "dob" value
 * @method text        getBio()          Returns the current record's "bio" value
 * @method string      getWebsiteUrl()   Returns the current record's "website_url" value
 * @method string      getFacebookUrl()  Returns the current record's "facebook_url" value
 * @method string      getTwitterUrl()   Returns the current record's "twitter_url" value
 * @method string      getYoutubeUrl()   Returns the current record's "youtube_url" value
 * @method Asset       getAsset()        Returns the current record's "Asset" value
 * @method AssetPerson setAssetId()      Sets the current record's "asset_id" value
 * @method AssetPerson setType()         Sets the current record's "type" value
 * @method AssetPerson setName()         Sets the current record's "name" value
 * @method AssetPerson setHeadline()     Sets the current record's "headline" value
 * @method AssetPerson setDob()          Sets the current record's "dob" value
 * @method AssetPerson setBio()          Sets the current record's "bio" value
 * @method AssetPerson setWebsiteUrl()   Sets the current record's "website_url" value
 * @method AssetPerson setFacebookUrl()  Sets the current record's "facebook_url" value
 * @method AssetPerson setTwitterUrl()   Sets the current record's "twitter_url" value
 * @method AssetPerson setYoutubeUrl()   Sets the current record's "youtube_url" value
 * @method AssetPerson setAsset()        Sets the current record's "Asset" value
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAssetPerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asset_person');
        $this->hasColumn('asset_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('headline', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('dob', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('bio', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('website_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('facebook_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('twitter_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('youtube_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Asset', array(
             'local' => 'asset_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}