<?php

/**
 * BaseView
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $asset
 * @property integer $section
 * @property string $ip
 * 
 * @method integer getAsset()   Returns the current record's "asset" value
 * @method integer getSection() Returns the current record's "section" value
 * @method string  getIp()      Returns the current record's "ip" value
 * @method View    setAsset()   Sets the current record's "asset" value
 * @method View    setSection() Sets the current record's "section" value
 * @method View    setIp()      Sets the current record's "ip" value
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseView extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('view');
        $this->hasColumn('asset', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('section', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ip', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 'disabled',
             ));
        $this->actAs($timestampable0);
    }
}