<?php

/**
 * BaseSectionAsset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $section_id
 * @property integer $asset_id
 * @property boolean $is_active
 * @property integer $display_order
 * @property Section $Section
 * @property Asset $Asset
 * 
 * @method integer      getSectionId()     Returns the current record's "section_id" value
 * @method integer      getAssetId()       Returns the current record's "asset_id" value
 * @method boolean      getIsActive()      Returns the current record's "is_active" value
 * @method integer      getDisplayOrder()  Returns the current record's "display_order" value
 * @method Section      getSection()       Returns the current record's "Section" value
 * @method Asset        getAsset()         Returns the current record's "Asset" value
 * @method SectionAsset setSectionId()     Sets the current record's "section_id" value
 * @method SectionAsset setAssetId()       Sets the current record's "asset_id" value
 * @method SectionAsset setIsActive()      Sets the current record's "is_active" value
 * @method SectionAsset setDisplayOrder()  Sets the current record's "display_order" value
 * @method SectionAsset setSection()       Sets the current record's "Section" value
 * @method SectionAsset setAsset()         Sets the current record's "Asset" value
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSectionAsset extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('section_asset');
        $this->hasColumn('section_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('asset_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Section', array(
             'local' => 'section_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Asset', array(
             'local' => 'asset_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}