<?php

/**
 * BaseAsset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $asset_type_id
 * @property integer $site_id
 * @property integer $user_id
 * @property integer $category_id
 * @property string $title
 * @property string $description
 * @property integer $display_order
 * @property boolean $is_active
 * @property integer $views
 * @property boolean $ugc
 * @property timestamp $date_start
 * @property timestamp $date_end
 * @property AssetType $AssetType
 * @property Doctrine_Collection $Categories
 * @property Category $Category
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $RelatedAssets
 * @property Doctrine_Collection $Sections
 * @property Site $Site
 * @property Doctrine_Collection $CategoryAsset
 * @property Doctrine_Collection $Display
 * @property AssetContent $AssetContent
 * @property AssetImage $AssetImage
 * @property AssetVideo $AssetVideo
 * @property AssetAudio $AssetAudio
 * @property AssetFile $AssetFile
 * @property AssetImageGallery $AssetImageGallery
 * @property AssetAudioGallery $AssetAudioGallery
 * @property AssetVideoGallery $AssetVideoGallery
 * @property AssetQuestionnaire $AssetQuestionnaire
 * @property AssetQuestion $AssetQuestion
 * @property AssetAnswer $AssetAnswer
 * @property AssetVote $AssetVote
 * @property AssetBroadcast $AssetBroadcast
 * @property AssetSeason $AssetSeason
 * @property AssetEpisode $AssetEpisode
 * @property AssetEvent $AssetEvent
 * @property AssetLink $AssetLink
 * @property AssetTweetMonitor $AssetTweetMonitor
 * @property AssetTweet $AssetTweet
 * @property AssetPerson $AssetPerson
 * @property Doctrine_Collection $Todos
 * 
 * @method integer             getAssetTypeId()        Returns the current record's "asset_type_id" value
 * @method integer             getSiteId()             Returns the current record's "site_id" value
 * @method integer             getUserId()             Returns the current record's "user_id" value
 * @method integer             getCategoryId()         Returns the current record's "category_id" value
 * @method string              getTitle()              Returns the current record's "title" value
 * @method string              getDescription()        Returns the current record's "description" value
 * @method integer             getDisplayOrder()       Returns the current record's "display_order" value
 * @method boolean             getIsActive()           Returns the current record's "is_active" value
 * @method integer             getViews()              Returns the current record's "views" value
 * @method boolean             getUgc()                Returns the current record's "ugc" value
 * @method timestamp           getDateStart()          Returns the current record's "date_start" value
 * @method timestamp           getDateEnd()            Returns the current record's "date_end" value
 * @method AssetType           getAssetType()          Returns the current record's "AssetType" value
 * @method Doctrine_Collection getCategories()         Returns the current record's "Categories" collection
 * @method Category            getCategory()           Returns the current record's "Category" value
 * @method sfGuardUser         getSfGuardUser()        Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getRelatedAssets()      Returns the current record's "RelatedAssets" collection
 * @method Doctrine_Collection getSections()           Returns the current record's "Sections" collection
 * @method Site                getSite()               Returns the current record's "Site" value
 * @method Doctrine_Collection getCategoryAsset()      Returns the current record's "CategoryAsset" collection
 * @method Doctrine_Collection getDisplay()            Returns the current record's "Display" collection
 * @method AssetContent        getAssetContent()       Returns the current record's "AssetContent" value
 * @method AssetImage          getAssetImage()         Returns the current record's "AssetImage" value
 * @method AssetVideo          getAssetVideo()         Returns the current record's "AssetVideo" value
 * @method AssetAudio          getAssetAudio()         Returns the current record's "AssetAudio" value
 * @method AssetFile           getAssetFile()          Returns the current record's "AssetFile" value
 * @method AssetImageGallery   getAssetImageGallery()  Returns the current record's "AssetImageGallery" value
 * @method AssetAudioGallery   getAssetAudioGallery()  Returns the current record's "AssetAudioGallery" value
 * @method AssetVideoGallery   getAssetVideoGallery()  Returns the current record's "AssetVideoGallery" value
 * @method AssetQuestionnaire  getAssetQuestionnaire() Returns the current record's "AssetQuestionnaire" value
 * @method AssetQuestion       getAssetQuestion()      Returns the current record's "AssetQuestion" value
 * @method AssetAnswer         getAssetAnswer()        Returns the current record's "AssetAnswer" value
 * @method AssetVote           getAssetVote()          Returns the current record's "AssetVote" value
 * @method AssetBroadcast      getAssetBroadcast()     Returns the current record's "AssetBroadcast" value
 * @method AssetSeason         getAssetSeason()        Returns the current record's "AssetSeason" value
 * @method AssetEpisode        getAssetEpisode()       Returns the current record's "AssetEpisode" value
 * @method AssetEvent          getAssetEvent()         Returns the current record's "AssetEvent" value
 * @method AssetLink           getAssetLink()          Returns the current record's "AssetLink" value
 * @method AssetTweetMonitor   getAssetTweetMonitor()  Returns the current record's "AssetTweetMonitor" value
 * @method AssetTweet          getAssetTweet()         Returns the current record's "AssetTweet" value
 * @method AssetPerson         getAssetPerson()        Returns the current record's "AssetPerson" value
 * @method Doctrine_Collection getTodos()              Returns the current record's "Todos" collection
 * @method Asset               setAssetTypeId()        Sets the current record's "asset_type_id" value
 * @method Asset               setSiteId()             Sets the current record's "site_id" value
 * @method Asset               setUserId()             Sets the current record's "user_id" value
 * @method Asset               setCategoryId()         Sets the current record's "category_id" value
 * @method Asset               setTitle()              Sets the current record's "title" value
 * @method Asset               setDescription()        Sets the current record's "description" value
 * @method Asset               setDisplayOrder()       Sets the current record's "display_order" value
 * @method Asset               setIsActive()           Sets the current record's "is_active" value
 * @method Asset               setViews()              Sets the current record's "views" value
 * @method Asset               setUgc()                Sets the current record's "ugc" value
 * @method Asset               setDateStart()          Sets the current record's "date_start" value
 * @method Asset               setDateEnd()            Sets the current record's "date_end" value
 * @method Asset               setAssetType()          Sets the current record's "AssetType" value
 * @method Asset               setCategories()         Sets the current record's "Categories" collection
 * @method Asset               setCategory()           Sets the current record's "Category" value
 * @method Asset               setSfGuardUser()        Sets the current record's "sfGuardUser" value
 * @method Asset               setRelatedAssets()      Sets the current record's "RelatedAssets" collection
 * @method Asset               setSections()           Sets the current record's "Sections" collection
 * @method Asset               setSite()               Sets the current record's "Site" value
 * @method Asset               setCategoryAsset()      Sets the current record's "CategoryAsset" collection
 * @method Asset               setDisplay()            Sets the current record's "Display" collection
 * @method Asset               setAssetContent()       Sets the current record's "AssetContent" value
 * @method Asset               setAssetImage()         Sets the current record's "AssetImage" value
 * @method Asset               setAssetVideo()         Sets the current record's "AssetVideo" value
 * @method Asset               setAssetAudio()         Sets the current record's "AssetAudio" value
 * @method Asset               setAssetFile()          Sets the current record's "AssetFile" value
 * @method Asset               setAssetImageGallery()  Sets the current record's "AssetImageGallery" value
 * @method Asset               setAssetAudioGallery()  Sets the current record's "AssetAudioGallery" value
 * @method Asset               setAssetVideoGallery()  Sets the current record's "AssetVideoGallery" value
 * @method Asset               setAssetQuestionnaire() Sets the current record's "AssetQuestionnaire" value
 * @method Asset               setAssetQuestion()      Sets the current record's "AssetQuestion" value
 * @method Asset               setAssetAnswer()        Sets the current record's "AssetAnswer" value
 * @method Asset               setAssetVote()          Sets the current record's "AssetVote" value
 * @method Asset               setAssetBroadcast()     Sets the current record's "AssetBroadcast" value
 * @method Asset               setAssetSeason()        Sets the current record's "AssetSeason" value
 * @method Asset               setAssetEpisode()       Sets the current record's "AssetEpisode" value
 * @method Asset               setAssetEvent()         Sets the current record's "AssetEvent" value
 * @method Asset               setAssetLink()          Sets the current record's "AssetLink" value
 * @method Asset               setAssetTweetMonitor()  Sets the current record's "AssetTweetMonitor" value
 * @method Asset               setAssetTweet()         Sets the current record's "AssetTweet" value
 * @method Asset               setAssetPerson()        Sets the current record's "AssetPerson" value
 * @method Asset               setTodos()              Sets the current record's "Todos" collection
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAsset extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asset');
        $this->hasColumn('asset_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('site_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('views', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ugc', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('date_start', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('date_end', 'timestamp', null, array(
             'type' => 'timestamp',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AssetType', array(
             'local' => 'asset_type_id',
             'foreign' => 'id'));

        $this->hasMany('Category as Categories', array(
             'refClass' => 'CategoryAsset',
             'local' => 'asset_id',
             'foreign' => 'category_id'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('RelatedAsset as RelatedAssets', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasMany('Section as Sections', array(
             'refClass' => 'SectionAsset',
             'local' => 'asset_id',
             'foreign' => 'section_id'));

        $this->hasOne('Site', array(
             'local' => 'site_id',
             'foreign' => 'id'));

        $this->hasMany('CategoryAsset', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasMany('Display', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetContent', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetImage', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetVideo', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetAudio', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetFile', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetImageGallery', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetAudioGallery', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetVideoGallery', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetQuestionnaire', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetQuestion', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetAnswer', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetVote', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetBroadcast', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetSeason', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetEpisode', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetEvent', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetLink', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetTweetMonitor', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetTweet', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasOne('AssetPerson', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $this->hasMany('Todo as Todos', array(
             'local' => 'id',
             'foreign' => 'asset_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $taggable0 = new Taggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
        $this->actAs($taggable0);
    }
}