<?php

/**
 * BaseAssetType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $model
 * @property integer $display_order
 * @property boolean $is_active
 * @property boolean $is_visible
 * @property boolean $upload_input
 * @property Doctrine_Collection $Assets
 * 
 * @method string              getTitle()         Returns the current record's "title" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method string              getModel()         Returns the current record's "model" value
 * @method integer             getDisplayOrder()  Returns the current record's "display_order" value
 * @method boolean             getIsActive()      Returns the current record's "is_active" value
 * @method boolean             getIsVisible()     Returns the current record's "is_visible" value
 * @method boolean             getUploadInput()   Returns the current record's "upload_input" value
 * @method Doctrine_Collection getAssets()        Returns the current record's "Assets" collection
 * @method AssetType           setTitle()         Sets the current record's "title" value
 * @method AssetType           setDescription()   Sets the current record's "description" value
 * @method AssetType           setModel()         Sets the current record's "model" value
 * @method AssetType           setDisplayOrder()  Sets the current record's "display_order" value
 * @method AssetType           setIsActive()      Sets the current record's "is_active" value
 * @method AssetType           setIsVisible()     Sets the current record's "is_visible" value
 * @method AssetType           setUploadInput()   Sets the current record's "upload_input" value
 * @method AssetType           setAssets()        Sets the current record's "Assets" collection
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAssetType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asset_type');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('model', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('is_visible', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('upload_input', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->index('upload_input_idx', array(
             'fields' => 
             array(
              0 => 'upload_input',
             ),
             ));
        $this->index('is_visible_idx', array(
             'fields' => 
             array(
              0 => 'is_visible',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Asset as Assets', array(
             'local' => 'id',
             'foreign' => 'asset_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}