<?php

/**
 * BaseAssetAnswer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $asset_id
 * @property integer $asset_question_id
 * @property string $answer
 * @property integer $votes
 * @property Asset $Asset
 * @property AssetQuestion $AssetQuestion
 * 
 * @method integer       getAssetId()           Returns the current record's "asset_id" value
 * @method integer       getAssetQuestionId()   Returns the current record's "asset_question_id" value
 * @method string        getAnswer()            Returns the current record's "answer" value
 * @method integer       getVotes()             Returns the current record's "votes" value
 * @method Asset         getAsset()             Returns the current record's "Asset" value
 * @method AssetQuestion getAssetQuestion()     Returns the current record's "AssetQuestion" value
 * @method AssetAnswer   setAssetId()           Sets the current record's "asset_id" value
 * @method AssetAnswer   setAssetQuestionId()   Sets the current record's "asset_question_id" value
 * @method AssetAnswer   setAnswer()            Sets the current record's "answer" value
 * @method AssetAnswer   setVotes()             Sets the current record's "votes" value
 * @method AssetAnswer   setAsset()             Sets the current record's "Asset" value
 * @method AssetAnswer   setAssetQuestion()     Sets the current record's "AssetQuestion" value
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAssetAnswer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asset_answer');
        $this->hasColumn('asset_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('asset_question_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('answer', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('votes', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Asset', array(
             'local' => 'asset_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('AssetQuestion', array(
             'local' => 'asset_question_id',
             'foreign' => 'id'));
    }
}