<?php

/**
 * BaseDisplay
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $block_id
 * @property integer $asset_id
 * @property string $type
 * @property string $title
 * @property string $description
 * @property string $headline
 * @property string $file
 * @property string $label
 * @property string $url
 * @property string $target
 * @property string $image
 * @property blob $html
 * @property timestamp $date_start
 * @property timestamp $date_end
 * @property integer $display_order
 * @property boolean $is_active
 * @property Block $Block
 * @property Asset $Asset
 * 
 * @method integer   getBlockId()       Returns the current record's "block_id" value
 * @method integer   getAssetId()       Returns the current record's "asset_id" value
 * @method string    getType()          Returns the current record's "type" value
 * @method string    getTitle()         Returns the current record's "title" value
 * @method string    getDescription()   Returns the current record's "description" value
 * @method string    getHeadline()      Returns the current record's "headline" value
 * @method string    getFile()          Returns the current record's "file" value
 * @method string    getLabel()         Returns the current record's "label" value
 * @method string    getUrl()           Returns the current record's "url" value
 * @method string    getTarget()        Returns the current record's "target" value
 * @method string    getImage()         Returns the current record's "image" value
 * @method blob      getHtml()          Returns the current record's "html" value
 * @method timestamp getDateStart()     Returns the current record's "date_start" value
 * @method timestamp getDateEnd()       Returns the current record's "date_end" value
 * @method integer   getDisplayOrder()  Returns the current record's "display_order" value
 * @method boolean   getIsActive()      Returns the current record's "is_active" value
 * @method Block     getBlock()         Returns the current record's "Block" value
 * @method Asset     getAsset()         Returns the current record's "Asset" value
 * @method Display   setBlockId()       Sets the current record's "block_id" value
 * @method Display   setAssetId()       Sets the current record's "asset_id" value
 * @method Display   setType()          Sets the current record's "type" value
 * @method Display   setTitle()         Sets the current record's "title" value
 * @method Display   setDescription()   Sets the current record's "description" value
 * @method Display   setHeadline()      Sets the current record's "headline" value
 * @method Display   setFile()          Sets the current record's "file" value
 * @method Display   setLabel()         Sets the current record's "label" value
 * @method Display   setUrl()           Sets the current record's "url" value
 * @method Display   setTarget()        Sets the current record's "target" value
 * @method Display   setImage()         Sets the current record's "image" value
 * @method Display   setHtml()          Sets the current record's "html" value
 * @method Display   setDateStart()     Sets the current record's "date_start" value
 * @method Display   setDateEnd()       Sets the current record's "date_end" value
 * @method Display   setDisplayOrder()  Sets the current record's "display_order" value
 * @method Display   setIsActive()      Sets the current record's "is_active" value
 * @method Display   setBlock()         Sets the current record's "Block" value
 * @method Display   setAsset()         Sets the current record's "Asset" value
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDisplay extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('display');
        $this->hasColumn('block_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('asset_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('headline', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('label', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('target', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('html', 'blob', null, array(
             'type' => 'blob',
             ));
        $this->hasColumn('date_start', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('date_end', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Block', array(
             'local' => 'block_id',
             'foreign' => 'id'));

        $this->hasOne('Asset', array(
             'local' => 'asset_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}