<?php

/**
 * BaseAssetEpisode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $asset_id
 * @property integer $asset_season_id
 * @property string $headline
 * @property text $long_description
 * @property clob $transcription
 * @property string $number
 * @property string $director
 * @property string $actor
 * @property string $producer
 * @property string $writter
 * @property date $date_release
 * @property string $url
 * @property Asset $Asset
 * @property AssetSeason $AssetSeason
 * 
 * @method integer      getAssetId()          Returns the current record's "asset_id" value
 * @method integer      getAssetSeasonId()    Returns the current record's "asset_season_id" value
 * @method string       getHeadline()         Returns the current record's "headline" value
 * @method text         getLongDescription()  Returns the current record's "long_description" value
 * @method clob         getTranscription()    Returns the current record's "transcription" value
 * @method string       getNumber()           Returns the current record's "number" value
 * @method string       getDirector()         Returns the current record's "director" value
 * @method string       getActor()            Returns the current record's "actor" value
 * @method string       getProducer()         Returns the current record's "producer" value
 * @method string       getWritter()          Returns the current record's "writter" value
 * @method date         getDateRelease()      Returns the current record's "date_release" value
 * @method string       getUrl()              Returns the current record's "url" value
 * @method Asset        getAsset()            Returns the current record's "Asset" value
 * @method AssetSeason  getAssetSeason()      Returns the current record's "AssetSeason" value
 * @method AssetEpisode setAssetId()          Sets the current record's "asset_id" value
 * @method AssetEpisode setAssetSeasonId()    Sets the current record's "asset_season_id" value
 * @method AssetEpisode setHeadline()         Sets the current record's "headline" value
 * @method AssetEpisode setLongDescription()  Sets the current record's "long_description" value
 * @method AssetEpisode setTranscription()    Sets the current record's "transcription" value
 * @method AssetEpisode setNumber()           Sets the current record's "number" value
 * @method AssetEpisode setDirector()         Sets the current record's "director" value
 * @method AssetEpisode setActor()            Sets the current record's "actor" value
 * @method AssetEpisode setProducer()         Sets the current record's "producer" value
 * @method AssetEpisode setWritter()          Sets the current record's "writter" value
 * @method AssetEpisode setDateRelease()      Sets the current record's "date_release" value
 * @method AssetEpisode setUrl()              Sets the current record's "url" value
 * @method AssetEpisode setAsset()            Sets the current record's "Asset" value
 * @method AssetEpisode setAssetSeason()      Sets the current record's "AssetSeason" value
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAssetEpisode extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asset_episode');
        $this->hasColumn('asset_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('asset_season_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('headline', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('long_description', 'text', 610, array(
             'type' => 'text',
             'length' => 610,
             ));
        $this->hasColumn('transcription', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('number', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('director', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('actor', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('producer', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('writter', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('date_release', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Asset', array(
             'local' => 'asset_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('AssetSeason', array(
             'local' => 'asset_season_id',
             'foreign' => 'id'));
    }
}