<?php

/**
 * BaseMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $parent_id
 * @property integer $sender_user_id
 * @property integer $to_user_id
 * @property string $title
 * @property string $status
 * @property string $flag
 * @property string $email
 * @property Message $Parent
 * @property Doctrine_Collection $Children
 * 
 * @method integer             getParentId()       Returns the current record's "parent_id" value
 * @method integer             getSenderUserId()   Returns the current record's "sender_user_id" value
 * @method integer             getToUserId()       Returns the current record's "to_user_id" value
 * @method string              getTitle()          Returns the current record's "title" value
 * @method string              getStatus()         Returns the current record's "status" value
 * @method string              getFlag()           Returns the current record's "flag" value
 * @method string              getEmail()          Returns the current record's "email" value
 * @method Message             getParent()         Returns the current record's "Parent" value
 * @method Doctrine_Collection getChildren()       Returns the current record's "Children" collection
 * @method Message             setParentId()       Sets the current record's "parent_id" value
 * @method Message             setSenderUserId()   Sets the current record's "sender_user_id" value
 * @method Message             setToUserId()       Sets the current record's "to_user_id" value
 * @method Message             setTitle()          Sets the current record's "title" value
 * @method Message             setStatus()         Sets the current record's "status" value
 * @method Message             setFlag()           Sets the current record's "flag" value
 * @method Message             setEmail()          Sets the current record's "email" value
 * @method Message             setParent()         Sets the current record's "Parent" value
 * @method Message             setChildren()       Sets the current record's "Children" collection
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('message');
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sender_user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('to_user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('flag', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Message as Parent', array(
             'local' => 'parent_id',
             'foreign' => 'id'));

        $this->hasMany('Message as Children', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}