<?php

/**
 * BaseChannel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $organization_id
 * @property string $title
 * @property string $description
 * @property string $image_icon
 * @property string $image_thumb
 * @property string $url
 * @property boolean $is_active
 * @property Organization $Organization
 * @property Doctrine_Collection $ChannelProgram
 * @property Doctrine_Collection $Program
 * @property Doctrine_Collection $Programs
 * @property Doctrine_Collection $Schedules
 * 
 * @method integer             getOrganizationId()  Returns the current record's "organization_id" value
 * @method string              getTitle()           Returns the current record's "title" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method string              getImageIcon()       Returns the current record's "image_icon" value
 * @method string              getImageThumb()      Returns the current record's "image_thumb" value
 * @method string              getUrl()             Returns the current record's "url" value
 * @method boolean             getIsActive()        Returns the current record's "is_active" value
 * @method Organization        getOrganization()    Returns the current record's "Organization" value
 * @method Doctrine_Collection getChannelProgram()  Returns the current record's "ChannelProgram" collection
 * @method Doctrine_Collection getProgram()         Returns the current record's "Program" collection
 * @method Doctrine_Collection getPrograms()        Returns the current record's "Programs" collection
 * @method Doctrine_Collection getSchedules()       Returns the current record's "Schedules" collection
 * @method Channel             setOrganizationId()  Sets the current record's "organization_id" value
 * @method Channel             setTitle()           Sets the current record's "title" value
 * @method Channel             setDescription()     Sets the current record's "description" value
 * @method Channel             setImageIcon()       Sets the current record's "image_icon" value
 * @method Channel             setImageThumb()      Sets the current record's "image_thumb" value
 * @method Channel             setUrl()             Sets the current record's "url" value
 * @method Channel             setIsActive()        Sets the current record's "is_active" value
 * @method Channel             setOrganization()    Sets the current record's "Organization" value
 * @method Channel             setChannelProgram()  Sets the current record's "ChannelProgram" collection
 * @method Channel             setProgram()         Sets the current record's "Program" collection
 * @method Channel             setPrograms()        Sets the current record's "Programs" collection
 * @method Channel             setSchedules()       Sets the current record's "Schedules" collection
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChannel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('channel');
        $this->hasColumn('organization_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image_icon', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image_thumb', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organization', array(
             'local' => 'organization_id',
             'foreign' => 'id'));

        $this->hasMany('ChannelProgram', array(
             'local' => 'id',
             'foreign' => 'channel_id'));

        $this->hasMany('Program', array(
             'local' => 'id',
             'foreign' => 'channel_id'));

        $this->hasMany('Program as Programs', array(
             'refClass' => 'ChannelProgram',
             'local' => 'channel_id',
             'foreign' => 'program_id'));

        $this->hasMany('Schedule as Schedules', array(
             'local' => 'id',
             'foreign' => 'channel_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}