<?php

/**
 * BaseSection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $parent_section_id
 * @property integer $site_id
 * @property string $title
 * @property string $description
 * @property integer $display_order
 * @property boolean $is_homepage
 * @property boolean $is_editorial
 * @property boolean $is_visible
 * @property boolean $is_active
 * @property string $url
 * @property string $keywords
 * @property string $contact_email
 * @property Site $Site
 * @property Section $Parent
 * @property Doctrine_Collection $Assets
 * @property Doctrine_Collection $Editors
 * @property Doctrine_Collection $Children
 * @property Doctrine_Collection $Blocks
 * 
 * @method integer             getParentSectionId()   Returns the current record's "parent_section_id" value
 * @method integer             getSiteId()            Returns the current record's "site_id" value
 * @method string              getTitle()             Returns the current record's "title" value
 * @method string              getDescription()       Returns the current record's "description" value
 * @method integer             getDisplayOrder()      Returns the current record's "display_order" value
 * @method boolean             getIsHomepage()        Returns the current record's "is_homepage" value
 * @method boolean             getIsEditorial()       Returns the current record's "is_editorial" value
 * @method boolean             getIsVisible()         Returns the current record's "is_visible" value
 * @method boolean             getIsActive()          Returns the current record's "is_active" value
 * @method string              getUrl()               Returns the current record's "url" value
 * @method string              getKeywords()          Returns the current record's "keywords" value
 * @method string              getContactEmail()      Returns the current record's "contact_email" value
 * @method Site                getSite()              Returns the current record's "Site" value
 * @method Section             getParent()            Returns the current record's "Parent" value
 * @method Doctrine_Collection getAssets()            Returns the current record's "Assets" collection
 * @method Doctrine_Collection getEditors()           Returns the current record's "Editors" collection
 * @method Doctrine_Collection getChildren()          Returns the current record's "Children" collection
 * @method Doctrine_Collection getBlocks()            Returns the current record's "Blocks" collection
 * @method Section             setParentSectionId()   Sets the current record's "parent_section_id" value
 * @method Section             setSiteId()            Sets the current record's "site_id" value
 * @method Section             setTitle()             Sets the current record's "title" value
 * @method Section             setDescription()       Sets the current record's "description" value
 * @method Section             setDisplayOrder()      Sets the current record's "display_order" value
 * @method Section             setIsHomepage()        Sets the current record's "is_homepage" value
 * @method Section             setIsEditorial()       Sets the current record's "is_editorial" value
 * @method Section             setIsVisible()         Sets the current record's "is_visible" value
 * @method Section             setIsActive()          Sets the current record's "is_active" value
 * @method Section             setUrl()               Sets the current record's "url" value
 * @method Section             setKeywords()          Sets the current record's "keywords" value
 * @method Section             setContactEmail()      Sets the current record's "contact_email" value
 * @method Section             setSite()              Sets the current record's "Site" value
 * @method Section             setParent()            Sets the current record's "Parent" value
 * @method Section             setAssets()            Sets the current record's "Assets" collection
 * @method Section             setEditors()           Sets the current record's "Editors" collection
 * @method Section             setChildren()          Sets the current record's "Children" collection
 * @method Section             setBlocks()            Sets the current record's "Blocks" collection
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSection extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('section');
        $this->hasColumn('parent_section_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('site_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_homepage', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('is_editorial', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('is_visible', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('contact_email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Site', array(
             'local' => 'site_id',
             'foreign' => 'id'));

        $this->hasOne('Section as Parent', array(
             'local' => 'parent_section_id',
             'foreign' => 'id'));

        $this->hasMany('Asset as Assets', array(
             'refClass' => 'SectionAsset',
             'local' => 'section_id',
             'foreign' => 'asset_id'));

        $this->hasMany('sfGuardUser as Editors', array(
             'refClass' => 'SectionUser',
             'local' => 'section_id',
             'foreign' => 'user_id'));

        $this->hasMany('Section as Children', array(
             'local' => 'id',
             'foreign' => 'parent_section_id'));

        $this->hasMany('Block as Blocks', array(
             'local' => 'id',
             'foreign' => 'section_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => false,
             'fields' => 
             array(
              0 => 'title',
             ),
             'canEdit' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}