<?php

/**
 * BaseSiteUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $site_id
 * @property integer $user_id
 * @property Site $Site
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer     getSiteId()      Returns the current record's "site_id" value
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method Site        getSite()        Returns the current record's "Site" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method SiteUser    setSiteId()      Sets the current record's "site_id" value
 * @method SiteUser    setUserId()      Sets the current record's "user_id" value
 * @method SiteUser    setSite()        Sets the current record's "Site" value
 * @method SiteUser    setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSiteUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('site_user');
        $this->hasColumn('site_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Site', array(
             'local' => 'site_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}