<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $organization_id
 * @property string $title
 * @property string $description
 * @property boolean $is_active
 * @property Organization $Organization
 * @property Doctrine_Collection $CategoryAsset
 * @property Doctrine_Collection $Asset
 * 
 * @method integer             getOrganizationId()  Returns the current record's "organization_id" value
 * @method string              getTitle()           Returns the current record's "title" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method boolean             getIsActive()        Returns the current record's "is_active" value
 * @method Organization        getOrganization()    Returns the current record's "Organization" value
 * @method Doctrine_Collection getCategoryAsset()   Returns the current record's "CategoryAsset" collection
 * @method Doctrine_Collection getAsset()           Returns the current record's "Asset" collection
 * @method Category            setOrganizationId()  Sets the current record's "organization_id" value
 * @method Category            setTitle()           Sets the current record's "title" value
 * @method Category            setDescription()     Sets the current record's "description" value
 * @method Category            setIsActive()        Sets the current record's "is_active" value
 * @method Category            setOrganization()    Sets the current record's "Organization" value
 * @method Category            setCategoryAsset()   Sets the current record's "CategoryAsset" collection
 * @method Category            setAsset()           Sets the current record's "Asset" collection
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('organization_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Organization', array(
             'local' => 'organization_id',
             'foreign' => 'id'));

        $this->hasMany('CategoryAsset', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $this->hasMany('Asset', array(
             'refClass' => 'CategoryAsset',
             'local' => 'category_id',
             'foreign' => 'asset_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}