<?php

/**
 * BaseBlock
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $section_id
 * @property string $title
 * @property string $description
 * @property string $query
 * @property boolean $is_random
 * @property boolean $is_automatic
 * @property integer $items
 * @property string $items_order
 * @property integer $display_order
 * @property Section $Section
 * @property Doctrine_Collection $Displays
 * 
 * @method integer             getSectionId()     Returns the current record's "section_id" value
 * @method string              getTitle()         Returns the current record's "title" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method string              getQuery()         Returns the current record's "query" value
 * @method boolean             getIsRandom()      Returns the current record's "is_random" value
 * @method boolean             getIsAutomatic()   Returns the current record's "is_automatic" value
 * @method integer             getItems()         Returns the current record's "items" value
 * @method string              getItemsOrder()    Returns the current record's "items_order" value
 * @method integer             getDisplayOrder()  Returns the current record's "display_order" value
 * @method Section             getSection()       Returns the current record's "Section" value
 * @method Doctrine_Collection getDisplays()      Returns the current record's "Displays" collection
 * @method Block               setSectionId()     Sets the current record's "section_id" value
 * @method Block               setTitle()         Sets the current record's "title" value
 * @method Block               setDescription()   Sets the current record's "description" value
 * @method Block               setQuery()         Sets the current record's "query" value
 * @method Block               setIsRandom()      Sets the current record's "is_random" value
 * @method Block               setIsAutomatic()   Sets the current record's "is_automatic" value
 * @method Block               setItems()         Sets the current record's "items" value
 * @method Block               setItemsOrder()    Sets the current record's "items_order" value
 * @method Block               setDisplayOrder()  Sets the current record's "display_order" value
 * @method Block               setSection()       Sets the current record's "Section" value
 * @method Block               setDisplays()      Sets the current record's "Displays" collection
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlock extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('block');
        $this->hasColumn('section_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('query', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_random', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('is_automatic', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('items', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('items_order', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('display_order', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Section', array(
             'local' => 'section_id',
             'foreign' => 'id'));

        $this->hasMany('Display as Displays', array(
             'local' => 'id',
             'foreign' => 'block_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => false,
             'fields' => 
             array(
              0 => 'title',
             ),
             'canEdit' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}