<?php

/**
 * AssetSeasonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetSeasonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetSeasonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetSeason');
    }
}