<?php

/**
 * AssetTweetMonitorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetTweetMonitorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetTweetMonitorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetTweetMonitor');
    }
}