<?php

/**
 * AssetEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetEventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetEvent');
    }
}