<?php

/**
 * AssetAudio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AssetAudio extends BaseAssetAudio
{
  
  public function formatBytes($bytes) {
     if ($bytes < 1024) return $bytes.' B';
     elseif ($bytes < 1048576) return round($bytes / 1024, 2).' KB';
     elseif ($bytes < 1073741824) return round($bytes / 1048576, 2).' MB';
     elseif ($bytes < 1099511627776) return round($bytes / 1073741824, 2).' GB';
     else return round($bytes / 1099511627776, 2).' TB';
  }

  public function convert() {

    $uploadDir = sfConfig::get('sf_upload_dir').'/assets/image';
    $uploadDirOriginal = sfConfig::get('sf_upload_dir').'/assets/audio/original';
    $uploadDirDefault = sfConfig::get('sf_upload_dir').'/assets/audio/default';
    if(!is_dir($uploadDir))
      mkdir($uploadDir, 0777);
    if(!is_dir($uploadDirOriginal))
      mkdir($uploadDirOriginal, 0777);
    if(!is_dir($uploadDirDefault))
      mkdir($uploadDirDefault, 0777);

    if($this->getOriginalFile()){
      $theFileName = $this->getOriginalFile();
      $theFileExtension = @strtolower(@end(@explode('.', $theFileName)));
      $theFileWithoutExtension = @current(@explode('.'.$theFileExtension, $theFileName));
      
      if($theFileExtension != "mp3"){
        exec('ffmpeg -i '.str_replace(" ","\ ", $uploadDirOriginal).'/'.$theFileName.' '.str_replace(" ","\ ", $uploadDirDefault).'/'.$theFileWithoutExtension.'.mp3');
      }
      else{
        copy($uploadDirOriginal.'/'.$theFileName, $uploadDirDefault.'/'.$theFileWithoutExtension.'.mp3');
      }
      
      $info = $this->ffmpegAudioInfo("$uploadDirOriginal/$theFileName");
      $this->setDuration($info["duration"]);
      $this->setExtension($theFileExtension);
      $this->setFile($theFileWithoutExtension);
      $this->setOriginalFile($theFileName);
      $this->setOriginalFileSize($this->formatBytes(filesize("$uploadDirOriginal/$theFileName")));
      $this->setExtension($theFileExtension);
      $this->save();
    }
    return true;
  }

  public function ffmpegAudioInfo($file) {
    $file = str_replace(" ", "\ ", $file);
    $r = array();
    exec('ffmpeg -i '.$file.' 2>&1', $output);
    foreach ($output as $value) {
      if(strstr($value, 'Duration: ')) {
        $aux = explode("Duration: ", $value);
        $aux2 = explode(", ", $aux[1]);
        $r["duration"] = $aux2[0]; 
      }
      elseif(strstr($value, 'framerate')) {
        $aux = explode("framerate", $value);
        $aux2 = explode(": ", $aux[1]);
        $r["framerate"] = $aux2[1]; 
      }
    }
    return $r;
  }

  public function render(){

    return '<script type="text/javascript" src="http://cmais.com.br/js/jquery-ui-1.8.7/jquery-1.4.4.min.js"></script>
    <link href="http://cmais.com.br/portal/js/audioplayer/css/jplayer.blue.monday.css" rel="stylesheet" type="text/css" />
  <script type="text/javascript" src="http://cmais.com.br/portal/js/audioplayer/js/jquery.jplayer.min.js"></script>
  <script type="text/javascript">
   $(document).ready(function(){
    $("#jquery_jplayer_'.$this->getFile().'").jPlayer({
      ready: function () {
        $(this).jPlayer("setMedia", {
          mp3: "http://midia.cmais.com.br/assets/audio/default/'.$this->getFile().'.mp3",
        }).jPlayer("play");
      },
      solution:"flash, html",
      swfPath: "http://cmais.com.br/js/audioplayer",
      supplied: "mp3"
    });
  });
  </script>
  <div id="jquery_jplayer_'.$this->getFile().'" class="jp-jplayer"></div>
    <div class="jp-audio">
      <div class="jp-type-single" style="border:1px solid #ccc;width: 615px;">
        <div id="jp_interface_1" class="jp-interface" style="height: 80px;">
          <ul class="jp-controls">
            <li><a href="#" class="jp-play" tabindex="1" style="left:44px;top:10px;">play</a></li>
	          <li><a href="#" class="jp-pause" tabindex="1" style="left:44px;top:10px;">pause</a></li>
	          <li><a href="#" class="jp-stop" tabindex="1" style="left:121px;top:16px;">stop</a></li>
	          <li><a href="#" class="jp-mute" tabindex="1" style="left:70%;top:22px;">mute</a></li>
	          <li><a href="#" class="jp-unmute" tabindex="1" style="left:70%;top:22px;">unmute</a></li>
          </ul>
          <div class="jp-progress" style="left:20px;top:56px; width: 94%;">
            <div class="jp-seek-bar">
              <div class="jp-play-bar"></div>
            </div>
          </div>
          <div class="jp-volume-bar" style="left:73%;top:27px;width:24%">
            <div class="jp-volume-bar-value"></div>
          </div>
          <div class="jp-current-time" style="left:20px;top:72px;"></div>
          <div class="jp-duration" style="left:20px;top:72px;width: 94%"></div>
        </div>
        <div id="jp_playlist_1" class="jp-playlist">
          <ul>
            <li>'.$this->Asset->getTitle().'</li>
          </ul>
        </div>
      </div>
  </div>';
  }

  public function render2(){

    return '<script type="text/javascript" src="/js/jquery-ui-1.8.7/jquery-1.4.4.min.js"></script><link href="/js/audioplayer/jPlayer.Blue.Monday.2.0.0/jplayer.blue.monday.css" rel="stylesheet" type="text/css" />
  <script type="text/javascript" src="/js/audioplayer/jquery.jplayer.js"></script>
  <script type="text/javascript">
   $(document).ready(function(){
    $("#jquery_jplayer_'.$this->getFile().'").jPlayer({
      ready: function () {
        $(this).jPlayer("setMedia", {
          mp3: "http://midia.cmais.com.br/assets/audio/default/'.$this->getFile().'.mp3",
        });
      },
      swfPath: "http://cmais.com.br/js/audioplayer",
      supplied: "mp3"
    });
  });
  </script>
  <div id="jquery_jplayer_'.$this->getFile().'" class="jp-jplayer"></div>
    <div class="jp-audio">
      <div class="jp-type-single">
        <div id="jp_interface_1" class="jp-interface">
          <ul class="jp-controls">
            <li><a href="#" class="jp-play" tabindex="1">play</a></li>
            <li><a href="#" class="jp-pause" tabindex="1">pause</a></li>
            <li><a href="#" class="jp-stop" tabindex="1">stop</a></li>
            <li><a href="#" class="jp-mute" tabindex="1">mute</a></li>
            <li><a href="#" class="jp-unmute" tabindex="1">unmute</a></li>
          </ul>
          <div class="jp-progress">
            <div class="jp-seek-bar">
              <div class="jp-play-bar"></div>
            </div>
          </div>
          <div class="jp-volume-bar">
            <div class="jp-volume-bar-value"></div>
          </div>
          <div class="jp-current-time"></div>
          <div class="jp-duration"></div>
        </div>
        <div id="jp_playlist_1" class="jp-playlist">
          <ul>
            <li>'.$this->Asset->getTitle().'</li>
          </ul>
        </div>
      </div>
  </div>';
  }

}