<?php

/**
 * Asset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Asset extends BaseAsset
{

  public function __toString()
  {
    return (string) $this->getTitle();
  }
  
  public function getThumbnail(){
    if($this->AssetType->getSlug() == "image")
      return "<img title='".$this->getTitle()."' alt='".$this->getTitle()."' src='http://midia.cmais.com.br/assets/image/thumbnail/".$this->AssetImage->getFile().".jpg' />";
    elseif($this->AssetType->getSlug() == "video"){
      if(!$this->AssetVideo->getYoutubeId())
        return "<img title='".$this->getTitle()."' alt='".$this->getTitle()."' src='/images/youtube_wait.jpg' />";
      else
        return "<img title='".$this->getTitle()."' alt='".$this->getTitle()."' src='http://img.youtube.com/vi/".$this->AssetVideo->getYoutubeId()."/1.jpg' />";
    }
    else{
      return $this->AssetType->getSlug();
    }
  }

  public function getThumbnail2(){
    if($this->AssetType->getSlug() == "image")
      return "http://midia.cmais.com.br/assets/image/thumbnail/".$this->AssetImage->getFile().".jpg";
    elseif($this->AssetType->getSlug() == "video"){
      if(!$this->AssetVideo->getYoutubeId())
        return "/images/youtube_wait.jpg";
      else
        return "http://img.youtube.com/vi/".$this->AssetVideo->getYoutubeId()."/1.jpg";
    }
    else{
      return $this->AssetType->getSlug();
    }
  }

  public function retriveRelatedAssetsByRelationType($type){
    $r = array();
    if($this->getId() > 0 && $type){
      $r = Doctrine_Query::create()
      ->select('a.*, ra.id related_asset_id, ra.type related_asset_type, ra.description related_asset_description')
      ->from('Asset a, RelatedAsset ra')
      ->where('a.id = ra.asset_id')
      ->andWhere('ra.parent_asset_id = ?', (int)$this->getId())
      ->andWhere('ra.type = ?', $type)
      ->groupBy('ra.id')
      ->orderBy('ra.display_order')
      ->execute();
    }
    return $r;
  }

  public function retriveRelatedAssetsByAssetTypeId22($type){
    $r = array();
    if($this->getId() > 0 && $type){
      $r = Doctrine_Query::create()
      ->select('a.*, ra.id related_asset_id, ra.type related_asset_type, ra.description related_asset_description')
      ->from('Asset a, RelatedAsset ra')
      ->where('a.id = ra.asset_id')
      ->andWhere('ra.parent_asset_id = ?', (int)$this->getId())
      ->andWhere('a.asset_type_id = ?', (int)$type)
      ->andWhere('a.is_active = 1')
      ->andWhere('a.date_start IS NULL OR a.date_start <= ?', date("Y-m-d H:i:s"))
      ->groupBy('ra.id')
      ->orderBy('ra.display_order')
      ->execute();
    }
    return $r;
  }

  public function retriveRelatedAssetsByAssetTypeId($type){
    $r = array();
    if($this->getId() > 0 && $type){
      $r = Doctrine_Query::create()
      ->select('a.*, ra.id related_asset_id, ra.type related_asset_type, ra.description related_asset_description')
      ->from('Asset a, RelatedAsset ra')
      ->where('a.id = ra.asset_id')
      ->andWhere('ra.parent_asset_id = ?', (int)$this->getId())
      ->andWhere('a.asset_type_id = ?', (int)$type)
      ->groupBy('ra.id')
      ->orderBy('ra.display_order')
      ->execute();
    }
    return $r;
  }

  public function retriveRelatedAssets(){
    $r = array();
    if($this->getId() > 0){
      $r = Doctrine_Query::create()
      ->select('a.*, ra.id related_asset_id, ra.type related_asset_type, ra.description related_asset_description')
      ->from('Asset a, RelatedAsset ra')
      ->where('a.id = ra.asset_id')
      ->andWhere('ra.parent_asset_id = ?', (int)$this->getId())
      ->groupBy('ra.id')
      ->orderBy('ra.display_order')
      ->execute();
    }
    return $r;
  }

  public function retriveImageUrlByImageUsage($usage){
    if($this->getId() > 0){
      if($this->AssetType->getSlug() == "image"){
        if ($usage == 'original')
          return "http://midia.cmais.com.br/assets/image/".$usage."/".$this->AssetImage->getFile().".".$this->AssetImage->getExtension();
        else
          return "http://midia.cmais.com.br/assets/image/".$usage."/".$this->AssetImage->getFile().".jpg";
      }
      elseif($this->AssetType->getSlug() == "video"){
        if($this->AssetVideo->getYoutubeId() != ""){
          if($usage=="image-3")
            return "http://img.youtube.com/vi/".$this->AssetVideo->getYoutubeId()."/0.jpg";
          else
            return "http://img.youtube.com/vi/".$this->AssetVideo->getYoutubeId()."/1.jpg";
        }
      }
      else{
        $imgs = $this->retriveRelatedAssetsByAssetTypeId(2);
        if(count($imgs) > 0)
          return "http://midia.cmais.com.br/assets/image/".$usage."/".$imgs[0]->AssetImage->getFile().".jpg";
      }
    }
  }

  public function retriveUrl(){
    if($this->getId() > 0){
      return $this->Site->retriveUrl()."/".$this->getSlug();
      /*      
      if(count($this->Sections)>0)
        return $this->Sections[0]->retriveUrl()."/".$this->getSlug();
      else
        return $this->Site->retriveUrl()."/".$this->getSlug();
      */
    }
    else
      return "javascript:;";
  }
  
  public function retriveLabel(){
    if($this->Category->getTitle() != "")
      return $this->Category->getTitle();
  }

  public function retriveRelatedAssets2(){
    $tags = $this->getTags();
    if(count($tags)>0){
      $query = Doctrine_Query::create()
        ->select('a.*')
        ->from('Asset a')
        ->where('a.is_active = 1')
        ->andWhere('a.id != ?', (int)$this->getId());
      $i=0;
      foreach($tags as $t){
        if($i==0)
          $query->andWhere("(a.asset_type_id = 1 OR a.asset_type_id = 6) AND a.title like '%".$t."%' OR a.description like '%".$t."%'");
        else
          $query->orWhere("(a.asset_type_id = 1 OR a.asset_type_id = 6) AND a.title like '%".$t."%' OR a.description like '%".$t."%'");
        $i++;
      }
      return $query->orderBy('a.created_at desc')
        ->limit(5)
        ->orderBy('a.id desc')
        ->execute();
    }
  }

}
