<?php

/**
 * AssetFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetFile');
    }
}