<?php

/**
 * AssetContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AssetContent extends BaseAssetContent
{
  public function render(){
    
    $replaceVideo4201 = '<iframe class="youtube-player" type="text/html" width="420" height="236" src="http://www.youtube.com/embed/\\5?&rel=0&wmode=opaque" frameborder="0"></iframe>';
    //$replaceVideo4201 = '<object style="width: 420px; height: 236px;"><param name="movie" value="http://www.youtube.com/v/\\4?version=3&rel=0"><param name="allowFullScreen" value="true"><param name="allowScriptAccess" value="always"><embed src="http://www.youtube.com/v/\\4?version=3&rel=0" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="420" height="236"></object>';

    $replaceVideo6401 = '<iframe class="youtube-player" type="text/html" width="640" height="360" src="http://www.youtube.com/embed/\\4?&rel=0&wmode=opaque" frameborder="0"></iframe>';
    //$replaceVideo6401 = '<object style="width: 640px; height: 360px;"><param name="movie" value="http://www.youtube.com/v/\\4?version=3&rel=0"><param name="allowFullScreen" value="true"><param name="allowScriptAccess" value="always"><embed src="http://www.youtube.com/v/\\4?version=3&rel=0" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="640" height="360"></object>';
    
    $replaceVideo420 = '<iframe class="youtube-player" type="text/html" width="420" height="236" src="http://www.youtube.com/embed/\\5?&rel=0&wmode=opaque" frameborder="0"></iframe>';
    //$replaceVideo420 = '<object style="width: 420px; height: 236px;"><param name="movie" value="http://www.youtube.com/v/\\5?version=3&rel=0"><param name="allowFullScreen" value="true"><param name="allowScriptAccess" value="always"><embed src="http://www.youtube.com/v/\\5?version=3&rel=0" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="420" height="236"></object>';

    $replaceVideo640 = '<iframe class="youtube-player" type="text/html" width="640" height="360" src="http://www.youtube.com/embed/\\5?&rel=0&wmode=opaque" frameborder="0"></iframe>';
    //$replaceVideo640 = '<object style="width: 640px; height: 360px;"><param name="movie" value="http://www.youtube.com/v/\\5?version=3&rel=0"><param name="allowFullScreen" value="true"><param name="allowScriptAccess" value="always"><embed src="http://www.youtube.com/v/\\5?version=3&rel=0" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="640" height="360"></object>';
    
    $time=time();
    
    $replaceAudio = '
  <script type="text/javascript" src="http://cmais.com.br/js/jquery-ui-1.8.7/jquery-1.4.4.min.js"></script>
  <link href="http://cmais.com.br/js/audioplayer/jPlayer.Blue.Monday.2.0.0/jplayer.blue.monday.css" rel="stylesheet" type="text/css" />
  <script type="text/javascript" src="http://cmais.com.br/js/audioplayer/jquery.jplayer2.js"></script>
  <script type="text/javascript">
   $(document).ready(function(){
    $("#jquery_jplayer_\\2").jPlayer({
      ready: function () {
        $(this).jPlayer("setMedia", {
          mp3: "http://midia.cmais.com.br/assets/audio/default/\\2.mp3"
        });
      },
      play: function() { // To avoid both jPlayers playing together.
        $(this).jPlayer("pauseOthers");
      },
      swfPath: "http://cmais.com.br/js/audioplayer",
      supplied: "mp3",
      wmode: "window",
      cssSelectorAncestor: "#jp_container_\\2"
    });
  });
  </script>
  <div id="jquery_jplayer_\\2" class="jp-jplayer"></div>
    <div id="jp_container_\\2" class="jp-audio">
      <div class="jp-type-single">
        <div id="jp_interface_\\2" class="jp-interface">
          <ul class="jp-controls">
            <li><a href="#" class="jp-play" tabindex="1">play</a></li>
            <li><a href="#" class="jp-pause" tabindex="1">pause</a></li>
            <li><a href="#" class="jp-stop" tabindex="1">stop</a></li>
            <li><a href="#" class="jp-mute" tabindex="1">mute</a></li>
            <li><a href="#" class="jp-unmute" tabindex="1">unmute</a></li>
          </ul>
          <div class="jp-progress">
            <div class="jp-seek-bar">
              <div class="jp-play-bar"></div>
            </div>
          </div>
          <div class="jp-volume-bar">
            <div class="jp-volume-bar-value"></div>
          </div>
          <div class="jp-current-time"></div>
          <div class="jp-duration"></div>
        </div>
        <div id="jp_playlist_1" class="jp-playlist">
          <ul>
            <li>\\5</li>
          </ul>
        </div>
      </div>
  </div>';
  
    $replaceAudio2 = '
  <script type="text/javascript" src="http://cmais.com.br/js/jquery-ui-1.8.7/jquery-1.4.4.min.js"></script>
  <link href="http://cmais.com.br/js/audioplayer/jPlayer.Blue.Monday.2.0.0/jplayer.blue.monday.css" rel="stylesheet" type="text/css" />
  <script type="text/javascript" src="http://cmais.com.br/js/audioplayer/jquery.jplayer2.js"></script>
  <script type="text/javascript">
   $(document).ready(function(){
    $("#jquery_jplayer_\\2").jPlayer({
      ready: function () {
        $(this).jPlayer("setMedia", {
          mp3: "http://midia.cmais.com.br/assets/audio/default/\\2.mp3"
        });
      },
      play: function() { // To avoid both jPlayers playing together.
        $(this).jPlayer("pauseOthers");
      },
      swfPath: "http://cmais.com.br/js/audioplayer",
      supplied: "mp3",
      wmode: "window",
      cssSelectorAncestor: "#jp_container_\\2"
    });
  });
  </script>
  <div id="jquery_jplayer_\\2" class="jp-jplayer"></div>
    <div id="jp_container_\\2" class="jp-audio">
      <div class="jp-type-single">
        <div id="jp_interface_\\2" class="jp-interface">
          <ul class="jp-controls">
            <li><a href="#" class="jp-play" tabindex="1">play</a></li>
            <li><a href="#" class="jp-pause" tabindex="1">pause</a></li>
            <li><a href="#" class="jp-stop" tabindex="1">stop</a></li>
            <li><a href="#" class="jp-mute" tabindex="1">mute</a></li>
            <li><a href="#" class="jp-unmute" tabindex="1">unmute</a></li>
          </ul>
          <div class="jp-progress">
            <div class="jp-seek-bar">
              <div class="jp-play-bar"></div>
            </div>
          </div>
          <div class="jp-volume-bar">
            <div class="jp-volume-bar-value"></div>
          </div>
          <div class="jp-current-time"></div>
          <div class="jp-duration"></div>
        </div>
        <div id="jp_playlist_1" class="jp-playlist">
          <ul>
            <li>\\4</li>
          </ul>
        </div>
      </div>
  </div>';
    
    $content = $this->getContent();
    $content = preg_replace('/<img align="([^"]*)" alt="([^"]*)" src="\/images\/video-420.png" style="([^"]*)" youtubeid="([^"]*)" \/>/', $replaceVideo4201, $content);
    $content = preg_replace('/<img align="([^"]*)" alt="([^"]*)" src="\/images\/video-640.png" style="([^"]*)" youtubeid="([^"]*)" \/>/', $replaceVideo6401, $content);
    $content = preg_replace('/<img align="([^"]*)" alt="([^"]*)" border="([^"]*)" src="\/images\/video-420.png" style="([^"]*)" youtubeid="([^"]*)" \/>/', $replaceVideo420, $content);
    $content = preg_replace('/<img align="([^"]*)" alt="([^"]*)" border="([^"]*)" src="\/images\/video-640.png" style="([^"]*)" youtubeid="([^"]*)" \/>/', $replaceVideo640, $content);
    $content = preg_replace('/<img align="([^"]*)" alt="([^"]*)" border="([^"]*)" src="\/images\/audio.png" style="([^"]*)" title="([^"]*)" \/>/', $replaceAudio, $content);
    $content = preg_replace('/<img align="([^"]*)" alt="([^"]*)" src="\/images\/audio.png" style="([^"]*)" title="([^"]*)" \/>/', $replaceAudio2, $content);
    $content = preg_replace('/<img align="([^"]*)" alt="([^"]*)" border="([^"]*)" src="\/images\/audio.png" title="([^"]*)" \/>/', $replaceAudio2, $content);
    return $content;
  }
}

