<?php

/**
 * AssetVideoGalleryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetVideoGalleryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetVideoGalleryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetVideoGallery');
    }
}