<?php

/**
 * AssetVideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetVideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetVideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetVideo');
    }
}