<?php

/**
 * AssetLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetLinkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetLink');
    }
}