<?php

/**
 * AssetVoteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetVoteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetVoteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetVote');
    }
}