<?php

/**
 * AssetImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetImage');
    }
}