<?php

/**
 * AssetQuestionnaireTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetQuestionnaireTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetQuestionnaireTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetQuestionnaire');
    }
}