<?php

/**
 * AssetContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetContent');
    }
}