<?php

/**
 * AssetPersonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetPersonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetPersonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetPerson');
    }
}