<?php

/**
 * AssetBroadcastTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetBroadcastTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetBroadcastTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetBroadcast');
    }
}