<?php

/**
 * AssetTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetType');
    }
}