<?php

/**
 * AssetImageGalleryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetImageGalleryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetImageGalleryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetImageGallery');
    }
}