<?php

/**
 * AssetQuestionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetQuestionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetQuestionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetQuestion');
    }
}