<?php

/**
 * AssetEpisodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetEpisodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetEpisodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetEpisode');
    }
}