<?php

/**
 * AssetAudioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetAudioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetAudioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetAudio');
    }
}