<?php

/**
 * AssetTweetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AssetTweetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AssetTweetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AssetTweet');
    }
}