<?php

/**
 * CategoryAssetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryAssetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryAssetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryAsset');
    }
}