<?php

/**
 * Channel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Channel extends BaseChannel
{

  public function retriveUrl(){
    if($this->getUrl() != "")
      return $this->getUrl();
    elseif($this->getSlug() != "")
      return "http://".$this->getSlug().".cmais.com.br";
  }

  public function retriveLiveProgram(){
    $cs = Doctrine_Query::create()
      ->select('s.*')
      ->from('Schedule s')
      ->where('s.channel_id = ?', (int)$this->getId())
      ->andWhere('s.date_start <= ? AND s.date_end > ?', array(date('Y-m-d H:i:s', time()), date('Y-m-d H:i:s', time())))
      ->orderBy('s.date_start desc')
      ->limit(1)
      ->execute();
    return $cs;
  }

  public function retriveMenuPrograms(){
    $cs = Doctrine_Query::create()
      ->select('p.*')
      ->from('Program p, ChannelProgram cp')
      ->where('p.id = cp.program_id')
      ->andWhere('cp.channel_id = ?', (int)$this->getId())
      ->andWhere('p.is_in_menu = 1')
      ->orderBy('p.title')
      ->execute();
    return $cs;
  }

  public function retriveLivePrograms($limit, $id){
    if(!$limit)
      $limit = 1;
    if(!$id)
      $id = 0;
    $cs = Doctrine_Query::create()
      ->select('s.*')
      ->from('Schedule s')
      ->where('s.channel_id = ?', (int)$this->getId())
      ->andWhere('(s.date_start > ? AND s.date_end > ?)', array(date('Y-m-d H:i:s', time()), date('Y-m-d H:i:s', time())))
      ->andWhere('s.id != ?', (int)$id)
      ->orderBy('s.date_start')
      ->limit($limit)
      ->execute();
    return $cs;
  }

  public function retriveImportantPrograms($limit){
    if(!$limit)
      $limit = 1;
    $cs = Doctrine_Query::create()
      ->select('s.*')
      ->from('Schedule s')
      ->where('s.channel_id = ?', (int)$this->getId())
      ->andWhere('s.is_important = 1')
      ->andWhere('s.date_start >= ?', array(date('Y-m-d H:i:s', time())))
      ->orderBy('s.date_start')
      ->limit($limit)
      ->execute();
    return $cs;
  }

}
