<?php

/**
 * ChannelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChannelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChannelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Channel');
    }
}