<?php

/**
 * DisplayTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DisplayTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DisplayTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Display');
    }
}