<?php

/**
 * Display
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Display extends BaseDisplay
{

  public function postDelete($values)
  {
    $log = new Log();
    $log->setAction('Delete');
    if(sfContext::hasInstance())
      $log->setUserId(sfContext::getInstance()->getUser()->getGuardUser()->getId());
    $log->setSiteId($this->Block->Section->Site->getId());
    $log->setAsset($this->getId());
    $log->setAssetTitle($this->getTitle());  
    $log->setClass('Display');  
    $log->save();
  }

  public function postUpdate($values)
  {
    $log = new Log();
    $log->setAction('Update');
    if(sfContext::hasInstance())
      $log->setUserId(sfContext::getInstance()->getUser()->getGuardUser()->getId());
    $log->setSiteId($this->Block->Section->Site->getId());
    $log->setAsset($this->getId());
    $log->setAssetTitle($this->getTitle());  
    $log->setClass('Display');  
    $log->save();
  }

  public function postInsert($values)
  {
    $log = new Log();
    $log->setAction('Insert');
    if(sfContext::hasInstance())
      $log->setUserId(sfContext::getInstance()->getUser()->getGuardUser()->getId());
    $log->setSiteId($this->Block->Section->Site->getId());
    $log->setAsset($this->getId());
    $log->setAssetTitle($this->getTitle());  
    $log->setClass('Display');  
    $log->save();
  }

  public function retriveLabel(){
    if($this->getLabel() != "")
      return $this->getLabel();
    elseif($this->Asset->Category->getTitle() != "")
      return $this->Asset->Category->getTitle();    
    else
      return $this->Asset->getTitle();
  }

  public function retriveImageUrlByImageUsage($usage){
    if(!$usage)
      $usage = "default";
    if($this->getImage() != ""){
      return "http://midia.cmais.com.br/displays/".$this->getImage();
    }
    elseif($this->Asset->AssetType->getSlug() == "image"){
      return "http://midia.cmais.com.br/assets/image/".$usage."/".$this->Asset->AssetImage->getFile().".jpg";
    }
    elseif($this->Asset->AssetType->getSlug() == "video"){
      if($this->Asset->AssetVideo->getYoutubeId() != ""){
        if($usage=="image-3" || $usage=="image-3-b")
          return "http://img.youtube.com/vi/".$this->Asset->AssetVideo->getYoutubeId()."/0.jpg";
        else
          return "http://img.youtube.com/vi/".$this->Asset->AssetVideo->getYoutubeId()."/1.jpg";
      }
      else
        return false;
    }
    elseif($this->Asset->getId() > 0){
      $imgs = $this->Asset->retriveRelatedAssetsByAssetTypeId(2);
      if(count($imgs) > 0)
        return "http://midia.cmais.com.br/assets/image/".$usage."/".$imgs[0]->AssetImage->getFile().".jpg";
    }
  }

  public function retriveUrl(){
    if($this->url != "")
      return $this->url;
    elseif($this->Asset->getId() > 0)
      return $this->Asset->retriveUrl();
    else
      return "javascript:;";
  }
  
  /*
  public function retriveUrl(){
    if($this->url != "")
      return $this->url;
    elseif($this->Asset->getId() > 0)
      return "http://cmais.com.br/".$this->Asset->getSlug();
    else
      return "javascript:;";
  }
  */

}
