<?php

/**
 * ImageUsageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImageUsageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImageUsageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ImageUsage');
    }
}