<?php

/**
 * Program
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Program extends BaseProgram
{
  
  public function retriveUrl(){
    if($this->Site->getId() > 0)
      return $this->Site->retriveUrl();
    elseif($this->getSlug() != "")
      return "http://cmais.com.br/".$this->getSlug();
    else
      return "javascript:;";
  }

  public function retriveLiveImage(){
    if($this->getImageLive() != "")
      return "http://midia.cmais.com.br/programs/".$this->getImageLive();
    elseif($this->Channels[0]->getImageThumb() != "")
      return "http://midia.cmais.com.br/programs/".$this->Channels[0]->getImageThumb();
  }

}
