<?php

/**
 * RelatedAssetTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RelatedAssetTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RelatedAssetTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RelatedAssetType');
    }
}