<?php

/**
 * RelatedAssetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RelatedAssetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RelatedAssetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RelatedAsset');
    }
}