<?php

/**
 * Schedule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    astolfo
 * @subpackage model
 * @author     Emerson Estrella
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Schedule extends BaseSchedule
{
  
  public function retriveTitle(){
    if($this->getTitle() != "")
      return $this->getTitle();
    elseif($this->Program->getTitle() != "")
      return $this->Program->getTitle();
  }
  
  public function retriveDescription(){
    if($this->getDescriptionShort() != "")
      return $this->getDescriptionShort();
    elseif($this->getDescription() != "")
      return $this->getDescription();
    elseif($this->Program->getDescription() != "")
      return $this->Program->getDescription();
  }

  public function retriveDescription2(){
    if($this->getDescription() != "")
      return $this->getDescription();
    elseif($this->getDescriptionShort() != "")
      return $this->getDescriptionShort();
    elseif($this->Program->getDescription() != "")
      return $this->Program->getDescription();
  }

  public function retriveDescription3(){
    if($this->getDescription() != "")
      return $this->getDescription();
    elseif($this->getDescriptionShort() != "")
      return $this->getDescriptionShort();
    elseif($this->Program->getLongDescription() != "")
      return $this->Program->getLongDescription();
    elseif($this->Program->getDescription() != "")
      return $this->Program->getDescription();
  }

  public function retriveDescription4(){
    if($this->getDescription() != "")
      return $this->getDescription();
    elseif($this->getDescriptionShort() != "")
      return $this->getDescriptionShort();
  }

  public function retriveDescription5(){
    if($this->Program->getLongDescription() != "")
      return $this->Program->getLongDescription();
    elseif($this->Program->getDescription() != "")
      return $this->Program->getDescription();
  }

  public function retriveLiveImage(){
    if($this->getImage() != "")
      return "http://midia.cmais.com.br/displays/".$this->getImage();
    elseif($this->Program->getImageLive() != "")
      return "http://midia.cmais.com.br/programs/".$this->Program->getImageLive();
    elseif($this->Program->getImageThumb() != "")
      return "http://midia.cmais.com.br/programs/".$this->Program->getImageThumb();
  }

  public function retriveUrl(){
    if($this->url != "")
      return $this->url;
    else
      return $this->Program->retriveUrl();
  }

}
