<?php

/**
 * ScheduleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScheduleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScheduleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Schedule');
    }
}