<?php

/**
 * SectionAssetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SectionAssetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SectionAssetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SectionAsset');
    }
}