<?php

/**
 * SectionUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SectionUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SectionUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SectionUser');
    }
}