<?php

/**
 * SiteUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiteUser');
    }
}