<?php

/**
 * TweetMonitorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TweetMonitorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TweetMonitorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TweetMonitor');
    }
}