<?php

/**
 * ViewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ViewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ViewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('View');
    }
}